-- ============================================================================
-- 0004_realtime_cron.sql — NO-OP (migrazione sostituita)
--
-- In origine configurava pg_cron + pg_net per invocare la Supabase Edge Function
-- 'ingest-rt' ogni minuto. Queste estensioni e il Vault non sono disponibili su
-- PostgreSQL vanilla.
--
-- Nel deploy su VPS il polling GTFS-RT è gestito dal container `worker`
-- (worker/index.ts) tramite setInterval(60_000). Nessuna configurazione
-- database necessaria.
-- ============================================================================
